Update em_opls.mdp
Becksteinlab/MDPOW pull request #210
Opened 2022-06-30 03:07 UTC by VOD555

Correct the rcoul for CHARMM forcefield.

2022-06-30 09:18 UTC, orbeckst requested changes
I don't know why but this change seems to make a test file: grompp fails for the energy minimization part. Can you please check what's going on?

2022-06-30 09:24 UTC, iorga commented
This change is made on a file related to OPLS-AA, but the comment mentions CHARMM. @VOD555 could you please check this discrepancy? Is this change specific to OPLS or it should be also implemented in AMBER and CHARMM ? Thanks.

2022-07-01 18:59 UTC, orbeckst requested changes
The OPLSAA file looks ok, do you mean the CHARMM one?

2022-07-01 18:59 UTC, orbeckst commented on mdpow/templates/em_opls.mdp
> +rcoulomb                 = 1.2
This is the OPLS-AA file and 1.0 is correct for OPLS-AA.

2022-11-17 21:44 UTC, orbeckst commented on mdpow/templates/em_opls.mdp
> +rcoulomb                 = 1.2
Should have been in the CHARMM em MDP file. I made the changes.

2022-11-17 21:52 UTC, orbeckst approved these changes

2022-11-17 23:04 UTC, merged