changed dihedral atom group selection strings in test_dihedral.py
Becksteinlab/MDPOW pull request #218
Opened 2022-11-04 07:01 UTC by cadeduckworth

changed selection string format for dihedral atom groups:

- old format ('name *# or name *# ... ')
- new format ('name *#', 'name *#', ... )
- ensures that the atom group is not reordered alphanumerically
- the dihedral atom group will be analyzed properly in the order that is specified with this format

2022-11-04 07:06 UTC, cadeduckworth commented on mdpow/tests/test_dihedral.py
circvar needs to be revisited, pinning here to revisit reference values

2022-11-04 07:11 UTC, cadeduckworth commented on mdpow/tests/test_dihedral.py
>          results = dh_run.results
change assertion selection string to match ordered dihedral atom group selection or vice versa

2022-11-14 19:07 UTC, orbeckst requested changes
Looking good, just skip the troublesome test for Python < 3.8

EDIT: add entry to CHANGES

2022-11-17 16:04 UTC, orbeckst approved these changes
Thanks, looking all good.

I had asked for an update to CHANGES but I realized that your PR only addresses tests, which are internal and not user-facing, so we do not need a CHANGES entry.

2022-11-17 16:06 UTC, merged

2022-11-17 16:06 UTC, orbeckst commented
Well done, thank you @cadeduckworth !