Black formatting
Becksteinlab/MDPOW pull request #269
Opened 2023-08-21 13:07 UTC by a-ws-m

Use `black` to format two files, per [this request](https://github.com/Becksteinlab/MDPOW/pull/267#pullrequestreview-1585104049).

2023-08-22 14:27 UTC, orbeckst commented
Let's just switch _everything_ over to black #271 — I wanted to try that out in a project anyway.

@a-ws-m could you do the honors and blacken the whole code base, please?

2023-08-22 14:30 UTC, orbeckst requested changes
See #271 — please 
- blacken *all code* (in `mdpow`, `mdpow/tests`, and `scripts`)
- add yourself to AUTHORS
- add an entry to CHANGES

2023-08-22 15:20 UTC, a-ws-m commented
Done, I also:

* Added a `.git-blame-ignore-revs` per [the suggestion on that link you sent](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame).
* Added some files in `.vscode` so that users of that editor will be recommended to install `black` and have it format Python files upon saving.

2023-08-22 17:22 UTC, orbeckst approved these changes
Thank you! Looking good.

There are minor formatting changes for the CHANGES. You can just accept my "suggestions" from the comments.

My original plan was to squash-merge. However, if you're familiar with `git` then you could rewrite the history of this branch into **two commits**:
1. **all** black changes 
2. all other changes (AUTHORS, CHANGES, workflows, updated .git-blame-ignore-revs with the commit ID of (1))

Then I will be able to just merge without any need for any further changes.

Let me know if you want to rewrite the history. Otherwise I'll squash-merge after the code review suggestions are included and tests pass.

2023-08-22 17:27 UTC, orbeckst commented on .git-blame-ignore-revs
> +# Autoformat two files using `black`
(Unless you rewrite the history yourself and add the proper commit ID of the single commit with all black-generated changes. See review comment.)

2023-08-23 13:35 UTC, a-ws-m commented on .git-blame-ignore-revs
> +# Autoformat two files using `black`
Hi, I'm not confident I'll get that right to be honest with you! If it's OK, I'll leave it to you to change the hashes after merging.

2023-08-23 18:59 UTC, orbeckst commented on .git-blame-ignore-revs
> +# Autoformat two files using `black`
ok, will do

2023-08-25 21:27 UTC, orbeckst commented
I rewrote the history.

2023-08-25 21:46 UTC, merged

2023-08-25 21:46 UTC, orbeckst commented
Alright, we're now using `black`!